# In this CI, we should only work in reaction to a Merge Request
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

stages:
  - ci 

ci-job:
  services:
     - image:sandbox
  stage: ci
  script:
    - cd /it/wave
    - anod vcs --add-repo adareducer $CI_PROJECT_DIR
    - anod build adareducer
    - anod test  adareducer
    - e3-testsuite-report
        --failure-exit-code 1
        --xunit-output $CI_PROJECT_DIR/xunit_output.xml
        x86_64-linux/adareducer-test/results/new
